# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: My personal website
email: daniel.velasquez92@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm Daniel Velásquez Cabrera, Research Assistant at Universidad del Pacífico. I'm applying for a PhD in Economics by the end of this year. This is my personal website. 
baseurl: "" 
url: "" 
twitter_username: DanielVC1992
github_username:  dvelasquezc
author: Daniel Velásquez Cabrera

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

  
collections:
    research:
        output: true
    pages:
        output: true
    phdapplication:
        output: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
